In [2]:
import pandas as pd

In [22]:
df = pd.read_excel('data/Dataset-2.xlsx', sheet_name='Лист2')
df

,Date,Выручка,% доступности,MAU,Новые,Вернувшиеся,Количество операций,Ошибки,Средний чек,% доступности.1,MAU.1,Новые.1,Вернувшиеся.1,Количество операций.1,Ошибки.1,Средний чек.1,Доля платящих
0,02.сент,600000.000000,91,6.209971e+06,1271736,4.938235e+06,1218.323587,3715,492.480000,0.703224,0.884078,-0.069135,0.854884,0.342768,-0.34811,0.656413,NaN
1,03.сент,539800.000000,98,6.138791e+06,1447192,4.691599e+06,1747.030049,3200,308.981520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,05.сент,809765.000000,92,6.392179e+06,1195080,5.197099e+06,2017.756255,2915,401.319534,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,06.сент,978651.000000,100,7.697321e+06,1387697,6.309624e+06,2240.143369,1550,436.869806,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,07.сент,769542.000000,97,6.698070e+06,1752918,4.945152e+06,1578.282828,1501,487.581811,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,25.нояб,342363.574767,92,4.975691e+06,1928454,3.047237e+06,2308.402585,1869,148.311901,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,26.нояб,407430.019645,91,4.452613e+06,1071735,3.380878e+06,1461.988304,3215,278.682133,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,27.нояб,154015.002726,94,4.474282e+06,1989154,2.485128e+06,171.127781,14075,900.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,29.нояб,221581.639882,94,3.860038e+06,1539114,2.320924e+06,2062.706271,1380,107.422779,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,30.нояб,546252.628780,98,5.050528e+06,1703268,3.347260e+06,1451.800232,2065,376.258811,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
corr_dostupnosti = df['% доступности'].corr(df['Выручка'])
corr_mau = df['MAU'].corr(df['Выручка'])
corr_new = df['Новые'].corr(df['Выручка'])
corr_returned = df['Вернувшиеся'].corr(df['Выручка'])
corr_operation_count = df['Количество операций'].corr(df['Выручка'])
corr_errors = df['Ошибки'].corr(df['Выручка'])
corr_mid_check = df['Средний чек'].corr(df['Выручка'])
print(corr_dostupnosti)
print(corr_mau)
print(corr_new)
print(corr_returned)
print(corr_operation_count)
print(corr_errors)
print(corr_mid_check)

0.7032239575708845
0.8840775937186734
-0.06913465128212332
0.854884004355467
0.34276783902252717
-0.3481097246968701
0.6564130144758317